[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

evm_version = "shanghai" # simulation may be false positive on bsc (PUSH0 opcode support)

optimizer=true
optimizer_runs=1000

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

fs_permissions = [
    { access = "read-write", path = "./"},
    { access = "none", path = ".env"}
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
# Name "ethereum" breaks foundry configuration!
mainnet = "${ETHEREUM_RPC}"
arbitrum = "${ARBITRUM_RPC}"
polygon = "${POLYGON_RPC}"
optimism = "${OPTIMISM_RPC}"
base = "${BASE_RPC}"
bsc = "${BSC_RPC}"
avalanche = "${AVALANCHE_RPC}"
mantle = "${MANTLE_RPC}"
metis = "${METIS_RPC}"
sei = "${SEI_RPC}"
crossfi = "${CROSSFI_RPC}"

[etherscan]
mainnet = { key = "${ETHEREUM_TOKEN}", chain = "mainnet" }
arbitrum = { key = "${ARBITRUM_TOKEN}", chain = "arbitrum" }
polygon = { key = "${POLYGON_TOKEN}", chain = "polygon" }
optimism = { key = "${OPTIMISM_TOKEN}", chain = "optimism" }
base = { key = "${BASE_TOKEN}", chain = "base"}
bsc = { key = "${BSC_TOKEN}", chain = "bsc"}
avalanche = { key = "avascan", chain = "avalanche", url = "https://api.avascan.info/v2/network/mainnet/evm/43114/etherscan"}
mantle = { key = "verifyContract", chain = "mantle", url = "https://api.routescan.io/v2/network/mainnet/evm/5000/etherscan"}
metis = { key = "verifyContract", chain = "metis", url = "https://api.routescan.io/v2/network/mainnet/evm/1088/etherscan" }
sei = { key = "verifyContract", chain = "1329", url = "https://seitrace.com/pacific-1/api" }
